include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    - cast_nullable_to_non_nullable
    - always_use_package_imports

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint