name: repository_get_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  pedantic_mono: ^1.24.0+1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  envied_generator: ^0.5.4+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  generate: true
