name: repository_get_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  pedantic_mono: ^1.24.0+1

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
