name: Check And Test

on:
 push:
  branches:
    - '*'

jobs:
 test:
  name: Check the source code
  runs-on: ubuntu-latest
  
  steps:
   - uses: actions/checkout@v3
   - uses: subosito/flutter-action@v2.3.0
     with:
      flutter-version: '3.19.5'
   - name: Install dependencies
     run: flutter pub get

   - name: Format check
     run: dart format --output=none --set-exit-if-changed .

   - name: Lint check
     run: flutter analyze

   - name: Test
     run: flutter test